spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true # форматирование SQL при выводе в лог
  liquibase:
    change-log: classpath:db/changelog/db.changelog.sql # ссылка на changelog для liquibase
  jackson:
    serialization:
      indent_output: true # форматирование JSON в браузере
  mvc:
    favicon:
      enabled: false # убирает фавиконку спринга
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # подставка параметров в запрос при логгировании SQL
  file: C:\Users\litva\IdeaProjects\god\logs\Application.log # Файл, который будет отображаться в http://localhost:8080/actuator/logfile
datasource:
  god:
    h2:
      password:
      username: sa
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:file:C:/Users/litva/h2/goddb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
management:
  endpoints:
    web:
      exposure:
        include: ["metrics",
                  "health",
                  "env",
                  "shutdown",
                  "loggers",
                  "logfile",
                  "heapdump"] # Ендпоинты, которые доступны по ссылке http://localhost:8080/actuator/...