spring:
  security:
    user:
      password: user
      roles: USER
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true # форматирование SQL при выводе в лог
  datasource:
    password:
    username: sa
    url: jdbc:h2:file:C:/Users/litva/h2/goddb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog.sql # ссылка на changelog для liquibase
  jackson:
    serialization:
      indent_output: true # форматирование JSON в браузере
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE # подставка параметров в запрос при логгировании SQL